[project]
name = "typst-conda"
authors = ["Adrian Freund <adrian@freund.io>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-64", "osx-arm64"]

[feature.build.tasks]
build = "rattler-build build -c conda-forge -c https://prefix.dev/typst-forge --recipe "

[feature.build.dependencies]
rattler-build = ">=0.24.0"

[feature.lint.dependencies]
actionlint = "*"
check-jsonschema = "*"
shellcheck = "*"

[feature.pre-commit.dependencies]
pre-commit = "*"

[feature.pre-commit.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run -a"

[environments]
default = ["build", "lint", "pre-commit"]
build = ["build"]
pre-commit = ["pre-commit"]
lint = ["lint"]
