[project]
name = "typst-conda"
version = "0.1.0"
description = "Add a short description here"
authors = ["Adrian Freund <adrian@freund.io>"]
channels = ["conda-forge/label/typst_rc", "conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
build = "rattler-build build --recipe "

[dependencies]
rattler-build = ">=0.18.1,<0.19"
