context:
  name: "moderner-cv"
  version: "0.1.0"
  build_number: 0

package:
  name: "typst-${{ name }}"
  version: ${{ version }}

source:
  url: https://github.com/pavelzw/moderner-cv/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d845b0f8731aced8d2ad94599dbc1483746be113b249cbbffb0512d1efaf6974
  patches:
    - 0001-Change-template-file-import-to-typst-forge.patch

build:
  number: ${{ build_number }}
  noarch: generic
  string: ${{ hash }}_${{ build_number }}_${{ 'win' if win else 'unix' }}
  script:
    content:
      - if: not win
        then:
          - mkdir -p "$PREFIX/share/typst/packages/typst-forge/${{ name }}/${{ version }}"
          - cp -r typst.toml README.md lib.typ template/
              "$PREFIX/share/typst/packages/typst-forge/${{ name }}/${{ version }}"
        else:
          - mkdir "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}"
          - copy typst.toml "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}"
          - copy README.md "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}"
          - copy lib.typ "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}"
          - xcopy /E template\ "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}\template\"

tests:
  - script:
      - typst init @typst-forge/moderner-cv:0.1.0 project
      - cd project
      - typst compile example.typ

requirements:
  build:
    - __${{ 'win' if win else 'unix' }}
  run:
    - typst >=0.12.0rc1
    - __${{ 'win' if win else 'unix' }}

about:
  repository: https://github.com/pavelzw/moderner-cv
  license: MIT
  license_file: LICENSE
  summary: moderncv in typst
  description: |
    This is a typst adaptation of LaTeX's moderncv, a modern curriculum vitae class.
