context:
  name: "moderner-cv"
  version: "0.1.0"

package:
  name: "typst-${{ name }}"
  version: ${{ version }}

source:
  url: https://github.com/pavelzw/moderner-cv/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d845b0f8731aced8d2ad94599dbc1483746be113b249cbbffb0512d1efaf6974
  patches:
    - 0001-Change-imports-from-preview-to-typst-forge.patch

build:
  number: 4
  noarch: generic
  script:
    content:
      - mkdir -p "$PREFIX/share/typst/packages/typst-forge/${{ name }}/${{ version }}"
      - cp -r typst.toml README.md lib.typ template
          "$PREFIX/share/typst/packages/typst-forge/${{ name }}/${{ version }}"

tests:
  - script:
      - typst init @typst-forge/moderner-cv:0.1.0 project
      - cd project
      - typst compile example.typ

requirements:
  build:
    - __unix
  run:
    - typst >=0.12.0
    - typst-fontawesome =0.2.1

about:
  repository: https://github.com/pavelzw/moderner-cv
  license: MIT
  license_file: LICENSE
  summary: moderncv in typst
  description: |
    This is a typst adaptation of LaTeX's moderncv, a modern curriculum vitae class.
