context:
  name: "matryoshka"
  version: "0.1.0"
  build_number: 0

package:
  name: "typst-${{ name }}"
  version: ${{ version }}

source:
  url: https://github.com/freundTech/typst-matryoshka/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2f7a55c965846df53cd2f3ebcf381214056d28958ef78e49fe34ded79c30afb5

build:
  number: ${{ build_number }}
  noarch: generic
  string: ${{ hash }}_${{ build_number }}_${{ 'win' if win else 'unix' }}
  script:
    content:
      - cargo build --locked --release --target wasm32-unknown-unknown
      - if: not win
        then:
          - mkdir -p "$PREFIX/share/typst/packages/typst-forge/${{ name }}/${{ version }}"
          - cp typst.toml README.md lib.typ target/wasm32-unknown-unknown/release/matryoshka.wasm
              "$PREFIX/share/typst/packages/typst-forge/${{ name }}/${{ version }}"
        else:
          - mkdir "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}"
          - copy typst.toml "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}"
          - copy README.md "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}"
          - copy lib.typ "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}"
          - copy target\wasm32-unknown-unknown\release\matryoshka.wasm "%PREFIX%\Library\share\typst\packages\typst-forge\${{ name }}\${{ version }}"

tests:
  - script:
      - echo %TYPST_PACKAGE_PATH%
      - dir %TYPST_PACKAGE_PATH%
      - typst compile test.typ
    files:
      recipe:
        test.typ


requirements:
  build:
    - rust
    - rust-std-wasm32-unknown-unknown
    - __${{ 'win' if win else 'unix' }}
  run:
    - typst >=0.12.0rc1
    - __${{ 'win' if win else 'unix' }}

about:
  repository: https://github.com/freundTech/typst-matryoshka
  license: MIT
  license_file: LICENSE.txt
  summary: Run typst in typst
  description: |
    Matryoshka is a Typst package that allows you to compile Typst code to images from within Typst.
    This is especially useful for package authors that want to generate manuals with examples.
