context:
  name: "matryoshka"
  version: "0.1.0"

package:
  name: "typst-${{ name }}"
  version: ${{ version }}

source:
  url: https://github.com/freundTech/typst-matryoshka/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2f7a55c965846df53cd2f3ebcf381214056d28958ef78e49fe34ded79c30afb5

build:
  number: 3
  noarch: generic
  script:
    content:
      - cargo build --locked --release --target wasm32-unknown-unknown
      - mkdir -p "$PREFIX/share/typst/packages/typst-forge/${{ name }}/${{ version }}"
      - cp typst.toml README.md lib.typ target/wasm32-unknown-unknown/release/matryoshka.wasm
          "$PREFIX/share/typst/packages/typst-forge/${{ name }}/${{ version }}"

tests:
  - script:
      - typst compile test.typ
    files:
      recipe:
        test.typ


requirements:
  build:
    - rust
    - rust-std-wasm32-unknown-unknown
    - __unix
  run:
    - typst >=0.12.0

about:
  repository: https://github.com/freundTech/typst-matryoshka
  license: MIT
  license_file: LICENSE.txt
  summary: Run typst in typst
  description: |
    Matryoshka is a Typst package that allows you to compile Typst code to images from within Typst.
    This is especially useful for package authors that want to generate manuals with examples.
